# 📘 NumPy Assignment Solutions (1–10)

Welcome to my NumPy Assignment Notebook!

This notebook contains my complete solutions for Assignments **1–10**, covering NumPy fundamentals as well as advanced concepts. The objective was not only to solve the problems but also to understand the intuition behind every concept through practice and experimentation.

---

## 📚 Topics Covered

### Assignment 1
- Array Creation
- Array Modification

### Assignment 2
- Array Indexing
- Array Slicing

### Assignment 3
- Element-wise Array Operations
- Row-wise & Column-wise Operations

### Assignment 4
- Statistical Operations
- Array Normalization

### Assignment 5
- Broadcasting
- Working with Different Dimensions

### Assignment 6
- Matrix Multiplication
- Determinant
- Matrix Inverse
- Eigenvalues & Eigenvectors

### Assignment 7
- Reshaping Arrays
- Flattening Arrays

### Assignment 8
- Fancy Indexing
- Boolean Indexing

### Assignment 9
- Structured Arrays
- Euclidean Distance

### Assignment 10
- Masked Arrays
- Missing Data Handling

---

## 🎯 Learning Objectives

- Master NumPy array manipulation
- Perform efficient mathematical operations
- Understand broadcasting and vectorization
- Learn fundamental linear algebra operations
- Work with structured and masked arrays
- Strengthen problem-solving using NumPy
- Build intuition behind important Data Science concepts

---

> **Note:** These solutions are part of my Data Analytics learning journey. My focus is understanding concepts rather than simply obtaining the correct output.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [2]:
import numpy as np
arr = np.random.randint(1,21,(5,5))
print("Original Array \n",arr)
arr[:,2]= 1
print("Modified Array \n",arr)

Original Array 
 [[ 3  7  8 16 16]
 [14  3  6  6 14]
 [ 6 10 20  7 15]
 [ 2 10  7  8 12]
 [ 1  4 16  4 13]]
Modified Array 
 [[ 3  7  1 16 16]
 [14  3  1  6 14]
 [ 6 10  1  7 15]
 [ 2 10  1  8 12]
 [ 1  4  1  4 13]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arr2 = np.arange(1,17).reshape(4,4)
print("Original Array \n",arr2)
np.fill_diagonal(arr2,0)
print("Modified Array \n",arr2)

Original Array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
arr = np.arange(1,37).reshape(6,6)
print("Original array \n",arr)
print("Sliced array \n",arr[2:5,1:4])

Original array 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sliced array 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arr2 = np.random.randint(1, 30, (5, 5))
print("Original array:\n", arr2)

top_row = arr2[0, :]          # Entire top row
bottom_row = arr2[4, :]       # Entire bottom row
left_col = arr2[1:4, 0]       # Left column (excluding top and bottom corners)
right_col = arr2[1:4, 4]      # Right column (excluding top and bottom corners)

border_elements = np.concatenate((top_row, bottom_row, left_col, right_col))
print("\nSingle array of border elements:\n", border_elements)

Original array:
 [[ 6 28 20 14 29]
 [22 24 24 23 11]
 [ 2 26 10 22 17]
 [27  9 26 19 11]
 [ 6  3 20 19  8]]

Single array of border elements:
 [ 6 28 20 14 29  6  3 20 19  8 22  2 27 11 17 11]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
arr1 = np.random.randint(1,13,(3,4))
arr2 = np.random.randint(1,13,(3,4))
print("Original array 1 \n",arr1)
print("Original array 2 \n",arr2)
print("Addition of 2 array \n",arr1+arr2)
print("Substraction of 2 array \n",arr1-arr2)
print("Multiplication of 2 array \n",arr1*arr2)
print("Division of 2 array \n",arr1/arr2)

Original array 1 
 [[ 9  1  5  7]
 [ 3  1  4  8]
 [ 2  7 11  2]]
Original array 2 
 [[ 3 11  7  4]
 [ 7 12  3 12]
 [ 6  1  1  2]]
Addition of 2 array 
 [[12 12 12 11]
 [10 13  7 20]
 [ 8  8 12  4]]
Substraction of 2 array 
 [[  6 -10  -2   3]
 [ -4 -11   1  -4]
 [ -4   6  10   0]]
Multiplication of 2 array 
 [[27 11 35 28]
 [21 12 12 96]
 [12  7 11  4]]
Division of 2 array 
 [[ 3.          0.09090909  0.71428571  1.75      ]
 [ 0.42857143  0.08333333  1.33333333  0.66666667]
 [ 0.33333333  7.         11.          1.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
arr = np.arange(1, 17).reshape(4, 4)
print("Original array:\n", arr)

# Calculating sums using the axis parameter
row_sum = arr.sum(axis=1)
col_sum = arr.sum(axis=0)

print("\nRow-wise sum:", row_sum)
print("Column-wise sum:", col_sum)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [8]:
arr = np.random.randint(1,26,(5,5))
print("Original array \n",arr)
print("Mean: ",np.mean(arr))
print("Median: ",np.median(arr))
print("Standard Deviation",np.std(arr))
print("Variance :",np.var(arr))

Original array 
 [[13  6 19 14 15]
 [24 23  3 22 21]
 [15 17  6 18 11]
 [ 5 22 16 17  1]
 [12 14 17  7 20]]
Mean:  14.32
Median:  15.0
Standard Deviation 6.410740986812679
Variance : 41.0976


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
data = np.arange(1,10).reshape(3,3)
mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data - mean) / std_dev
print("Normalized data:\n", normalized_data)

Normalized data:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [10]:
arr = np.random.randint(1,10,(3,3))
print("Original array\n",arr)
one_d_arr = np.random.randint(1,11,(3,))
print("One dim array \n",one_d_arr)
result = arr+one_d_arr
print("\nResult after addition :\n", result)

Original array
 [[2 3 8]
 [9 6 1]
 [7 5 4]]
One dim array 
 [2 1 6]

Result after addition :
 [[ 4  4 14]
 [11  7  7]
 [ 9  6 10]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
arr = np.random.randint(1,20,(4,4))
print("Original array\n",arr)
one_d_arr = np.random.randint(1,11,(4,))
print("One dim array \n",one_d_arr)
print("Shape of one_d_arr:", one_d_arr.shape) 
result = arr - one_d_arr.reshape(4, 1)
print("\nResult after column-wise subtraction:\n", result)

Original array
 [[ 2 14  1  4]
 [ 9 14  6  6]
 [17 18  1  2]
 [16 16  9 10]]
One dim array 
 [7 2 2 4]
Shape of one_d_arr: (4,)

Result after column-wise subtraction:
 [[-5  7 -6 -3]
 [ 7 12  4  4]
 [15 16 -1  0]
 [12 12  5  6]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [12]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[ 3  6  1]
 [ 9 10  1]
 [ 7  3  3]]
Determinant: -82.00000000000001
Inverse:
[[-0.32926829  0.18292683  0.04878049]
 [ 0.24390244 -0.02439024 -0.07317073]
 [ 0.52439024 -0.40243902  0.29268293]]
Eigenvalues: [15.32455532 -2.          2.67544468]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [13]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[4 4 6]
 [7 8 5]]
Array 2:
[[6 2]
 [1 8]
 [1 2]]
Matrix multiplication result:
[[34 52]
 [55 88]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [14]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [15]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[12 10 15 15 16]
 [12  6 12  3 15]
 [ 3  8 10  6 10]
 [18  4 11 12  2]
 [ 2 14  5 14  6]]
Flattened array:
[12 10 15 15 16 12  6 12  3 15  3  8 10  6 10 18  4 11 12  2  2 14  5 14
  6]
Reshaped array:
[[12 10 15 15 16]
 [12  6 12  3 15]
 [ 3  8 10  6 10]
 [18  4 11 12  2]
 [ 2 14  5 14  6]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]] # here the first array list is the x and the second is the y
print("Corner elements:")
print(corners)

#using normal 
corners2 = np.array([array[0,0],array[0,-1],array[-1,0],array[-1,-1]])
print(corners2)

Original array:
[[ 6  4 14  1 15]
 [16  7 19 20 18]
 [ 2  6 13  1  9]
 [18  2 14 16 16]
 [ 5 16  8 16 19]]
Corner elements:
[ 6 15  5 19]
[ 6 15  5 19]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing set all elements greater then 10 to 1 and less then 10 to 0

In [37]:
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

#bool filtering 
array[array < 10] = 0
array[array >= 10] = 1
print("Modified array:")
print(array)

Original array:
[[18  6 12 15]
 [14  6  9  1]
 [11 17  8  8]
 [ 8 14  3  9]]
Modified array:
[[1 0 1 1]
 [1 0 0 0]
 [1 1 0 0]
 [0 1 0 0]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.



In [49]:
dt = [
    ("name" , "U10"),
    ("age","i4"),
    ("weight","f4")
    ]
st_array = np.array([("Priya",24,45.6),
                     ("Anas",22,85.8),
                     ("Govinda",23,65.2)],dtype=dt)
print(st_array)
sorted_array = np.sort(st_array,order="age")
print(sorted_array)


[('Priya', 24, 45.6) ('Anas', 22, 85.8) ('Govinda', 23, 65.2)]
[('Anas', 22, 85.8) ('Govinda', 23, 65.2) ('Priya', 24, 45.6)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [59]:
dt = [("x","f4"),
      ("y","f4")
      ]
st_array = np.array([(4.5,3.4),(6.2,6.8)],dtype=dt)
x1 = st_array["x"][0]
x2 = st_array["x"][1]
y1= st_array["y"][0]
y2 = st_array["y"][1]
distance = np.sqrt((x2-x1)**2 + (y2-y1)**2)
print("The euclidian distance is :",distance)

The euclidian distance is : 3.8013155



### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [ ]:
# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = np.ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[19  5 16  8]
 [16 10  6 14]
 [18 14  3 17]
 [ 3  1 14 15]]
Masked array:
[[-- 5 -- 8]
 [-- 10 6 --]
 [-- -- 3 --]
 [3 1 -- --]]
Sum of unmasked elements: 36


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [56]:
array = np.random.randint(1, 21, size=(3, 3))
masked_array = np.ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original Array \n",array)
print("Masked Array \n",masked_array)
unmasked_mean = np.mean(masked_array)
print("Mean of the unmasked array is: ",unmasked_mean)
masked_array = masked_array.filled(unmasked_mean)
print("Filled Array \n",masked_array)

Original Array 
 [[11 17  5]
 [ 8  7  6]
 [20 19  7]]
Masked Array 
 [[-- 17 5]
 [8 -- 6]
 [20 19 --]]
Mean of the unmasked array is:  12.5
Filled Array 
 [[12 17  5]
 [ 8 12  6]
 [20 19 12]]


# ✅ Conclusion

Successfully completed all **10 NumPy assignments** covering both beginner and advanced concepts.

---

## 📈 Concepts Learned

✔ Creating NumPy Arrays

✔ Array Indexing & Slicing

✔ Element-wise Operations

✔ Statistical Functions

✔ Broadcasting

✔ Matrix Multiplication

✔ Determinants

✔ Matrix Inverse

✔ Eigenvalues & Eigenvectors

✔ Reshaping & Flattening

✔ Fancy Indexing

✔ Boolean Indexing

✔ Structured Arrays

✔ Euclidean Distance

✔ Masked Arrays

---

## 💡 Key Takeaways

- Developed a strong understanding of NumPy fundamentals.
- Learned to think in terms of vectorized operations instead of loops.
- Explored Linear Algebra concepts using NumPy.
- Practiced efficient indexing and array manipulation.
- Built confidence in solving practical NumPy problems through self-learning.

---

## 🚀 Skills Gained

- NumPy Programming
- Vectorized Computation
- Mathematical Thinking
- Linear Algebra Basics
- Data Manipulation
- Problem Solving
- Debugging
- Self-Learning

---

## 📍 Learning Roadmap

```
Python Fundamentals ✅
NumPy ✅
Pandas ⏭️
Data Visualization ⏭️
Statistics ⏭️
Feature Engineering ⏭️
Exploratory Data Analysis ⏭️
Machine Learning ⏭️
Generative AI ⏭️
```

---

*"Small improvements every day lead to extraordinary results over time."* 🚀

**Next Milestone:** 📊 **Pandas for Data Analysis**