# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [2]:
import numpy as np
arr = np.random.randint(1,21,(5,5))
print("Original Array \n",arr)
arr[:,2]= 1
print("Modified Array \n",arr)

Original Array 
 [[ 6 19  6 11 16]
 [11 10  7  3 16]
 [16  1  5 15 17]
 [ 4  2 11 20  7]
 [ 7  3  3 16 20]]
Modified Array 
 [[ 6 19  1 11 16]
 [11 10  1  3 16]
 [16  1  1 15 17]
 [ 4  2  1 20  7]
 [ 7  3  1 16 20]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [30]:
arr2 = np.arange(1,17).reshape(4,4)
print("Original Array \n",arr2)
np.fill_diagonal(arr2,0)
print("Modified Array \n",arr2)

Original Array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [6]:
arr = np.arange(1,37).reshape(6,6)
print("Original array \n",arr)
print("Sliced array \n",arr[2:5,1:4])

Original array 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sliced array 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [25]:
arr2 = np.random.randint(1, 30, (5, 5))
print("Original array:\n", arr2)

top_row = arr2[0, :]          # Entire top row
bottom_row = arr2[4, :]       # Entire bottom row
left_col = arr2[1:4, 0]       # Left column (excluding top and bottom corners)
right_col = arr2[1:4, 4]      # Right column (excluding top and bottom corners)

border_elements = np.concatenate((top_row, bottom_row, left_col, right_col))
print("\nSingle array of border elements:\n", border_elements)

Original array:
 [[10  1 23 13  5]
 [25 19 22  7  3]
 [11  6 14  6  5]
 [13 14 29 17 24]
 [ 8 10  5  2 23]]

Single array of border elements:
 [10  1 23 13  5  8 10  5  2 23 25 11 13  3  5 24]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [26]:
arr1 = np.random.randint(1,13,(3,4))
arr2 = np.random.randint(1,13,(3,4))
print("Original array 1 \n",arr1)
print("Original array 2 \n",arr2)
print("Addition of 2 array \n",arr1+arr2)
print("Substraction of 2 array \n",arr1-arr2)
print("Multiplication of 2 array \n",arr1*arr2)
print("Division of 2 array \n",arr1/arr2)

Original array 1 
 [[10  1  8  4]
 [ 8  5  3 11]
 [ 4  2  6  2]]
Original array 2 
 [[10  2  7  3]
 [ 2  9 11  1]
 [ 1 12  2  5]]
Addition of 2 array 
 [[20  3 15  7]
 [10 14 14 12]
 [ 5 14  8  7]]
Substraction of 2 array 
 [[  0  -1   1   1]
 [  6  -4  -8  10]
 [  3 -10   4  -3]]
Multiplication of 2 array 
 [[100   2  56  12]
 [ 16  45  33  11]
 [  4  24  12  10]]
Division of 2 array 
 [[ 1.          0.5         1.14285714  1.33333333]
 [ 4.          0.55555556  0.27272727 11.        ]
 [ 4.          0.16666667  3.          0.4       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [38]:
arr = np.arange(1, 17).reshape(4, 4)
print("Original array:\n", arr)

# Calculating sums using the axis parameter
row_sum = arr.sum(axis=1)
col_sum = arr.sum(axis=0)

print("\nRow-wise sum:", row_sum)
print("Column-wise sum:", col_sum)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [35]:
arr = np.random.randint(1,26,(5,5))
print("Original array \n",arr)
print("Mean: ",np.mean(arr))
print("Median: ",np.median(arr))
print("Standard Deviation",np.std(arr))
print("Variance :",np.var(arr))

Original array 
 [[20 19 17 23 14]
 [ 6 19 16 13 21]
 [ 2 10 21  8 16]
 [19 16 22 16 10]
 [12  4 10 24 20]]
Mean:  15.12
Median:  16.0
Standard Deviation 5.935115837117251
Variance : 35.22560000000001


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [37]:
data = np.arange(1,10).reshape(3,3)
mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data - mean) / std_dev
print("Normalized data:\n", normalized_data)

Normalized data:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [59]:
arr = np.random.randint(1,10,(3,3))
print("Original array\n",arr)
one_d_arr = np.random.randint(1,11,(3,))
print("One dim array \n",one_d_arr)
result = arr+one_d_arr
print("\nResult after addition :\n", result)

Original array
 [[7 9 1]
 [2 5 2]
 [6 7 8]]
One dim array 
 [9 5 1]

Result after addition :
 [[16 14  2]
 [11 10  3]
 [15 12  9]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
arr = np.random.randint(1,20,(4,4))
print("Original array\n",arr)
one_d_arr = np.random.randint(1,11,(4,))
print("One dim array \n",one_d_arr)
print("Shape of one_d_arr:", one_d_arr.shape) 
result = arr - one_d_arr.reshape(4, 1)
print("\nResult after column-wise subtraction:\n", result)

Original array
 [[ 3 16 12 13]
 [10  6  1 10]
 [ 4  8  1 14]
 [18  7  8  9]]
One dim array 
 [9 2 8 1]
Shape of one_d_arr: (4,)

Result after column-wise subtraction:
 [[-6  7  3  4]
 [ 8  4 -1  8]
 [-4  0 -7  6]
 [17  6  7  8]]
