# 📊 NumPy

## Introduction

NumPy (Numerical Python) is the fundamental library for numerical computing in Python. It provides a powerful N-dimensional array object along with mathematical, statistical, and logical operations that are significantly faster and more memory-efficient than Python lists. NumPy serves as the foundation for libraries such as Pandas, Matplotlib, Scikit-learn, and TensorFlow, making it an essential skill for Data Analysis, Data Science, and Machine Learning.

In [2]:
import numpy as np

In [3]:
# creating array 1d 
arr1 = np.array([1,2,3,4,5,6])

In [4]:
print(arr1)
print(type(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
# a 1d array has empty and i colm 
arr1.shape

(6,)

In [10]:
# in order to make a 1d into 2d we use reshape
arr2 = arr1.reshape([2,3])
arr3 = arr1.reshape(3,2)

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#arange is used to generate numbers we can also add (start,stop,step)
arr4 = np.arange(0,9).reshape(3,3)

In [14]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
#more built in functions 
arr_zeros = np.zeros(12).reshape(4,3) #creates an array of zeros 
arr_one = np.ones(12).reshape(4,3) # creates an array of ones 
arr_eye = np.eye(10) # creates a matrix with dignal as 1 from top left to bottom right 

In [31]:
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
arr_one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
arr_eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division : ", arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]


In [36]:
## Universal Function
arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
# modifying the elements 
arr=np.array([1,2,3,4,5,6]).reshape(2,3)
arr[0,0]=100
print(arr)

[[100   2   3]
 [  4   5   6]]


In [70]:
arr=np.array([1,2,3,4,5,6]).reshape(2,3)
arr[1:]=100
print(arr)

[[  1   2   3]
 [100 100 100]]


In [37]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#first element 
arr[0][0]

np.int64(1)

In [53]:
# suppose u want 7,8,11,12
print(arr[1:,2:],"\n\n\n\n\n") # first comma defines rows after comma defines columns 

print(arr[0:2,2:])

[[ 7  8]
 [11 12]] 





[[3 4]
 [7 8]]


In [54]:
### statistical concepts--Normalization
### to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [56]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [57]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [58]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[data>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)] # using and & and or |

array([5, 6, 7, 8])

# ✅ Conclusion

In this notebook, I explored the core concepts of NumPy, including array creation, indexing, slicing, reshaping, vectorized operations, universal functions, statistical methods, and logical operations. These concepts demonstrate how NumPy enables efficient numerical computation and simplifies data manipulation. With this foundation, I am well-prepared to work with larger datasets using Pandas and continue my journey into Data Analysis, Machine Learning, and Artificial Intelligence.